import { Action } from "solana-agent-kit";
import { z } from "zod";
import { donutFetchTokenDetailedReport } from "../tools";

const donutRugcheckAction: Action = {
  name: "DONUT_RUGCHECK",
  description:
    "Get token in depth token analysis to determine if token is a rug pull",
  similes: [
    "check rug pull",
    "rug pull check",
    "rug pull detector",
    "rug pull scanner",
    "rug pull alert",
  ],
  examples: [
    [
      {
        input: {
          tokenId: "jup",
        },
        output: {
          status: "success",
          message: {
            status: "success",
            response: {
              mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
              tokenProgram: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
              creator: null,
              creatorBalance: 0,
              token: {
                mintAuthority: null,
                supply: 6999216038334110,
                decimals: 6,
                isInitialized: true,
                freezeAuthority: null,
              },
              token_extensions: null,
              tokenMeta: {
                name: "Jupiter",
                symbol: "JUP",
                uri: "https://static.jup.ag/jup/metadata.json",
                mutable: true,
                updateAuthority: "61aq585V8cR2sZBeawJFt2NPqmN7zDi1sws4KLs5xHXV",
              },
              topHolders: [
                {
                  address: "26ddLrqXDext6caX1gRxARePN4kzajyGiAUz9JmzmTGQ",
                  amount: 2032700001514268,
                  decimals: 6,
                  pct: 29.041823975447294,
                  uiAmount: 2032700001.514268,
                  uiAmountString: "2032700001.514268",
                  owner: "61aq585V8cR2sZBeawJFt2NPqmN7zDi1sws4KLs5xHXV",
                  insider: false,
                },
                {
                  address: "6G4XDSge4txj5tBkA5gZqefXXE3BRxqA37Yb1pmrHv6N",
                  amount: 1700000000001000,
                  decimals: 6,
                  pct: 24.288434457377008,
                  uiAmount: 1700000000.001,
                  uiAmountString: "1700000000.001",
                  owner: "EXJHiMkj6NRFDfhWBMKccHNwdSpCT7tdvQeRf87yHm6T",
                  insider: false,
                },
                {
                  address: "K6U4dQ8jANMEqQQycXYiDcf3172NGefpQBzdDbavQbA",
                  amount: 471224821640285,
                  decimals: 6,
                  pct: 6.732537173583824,
                  uiAmount: 471224821.640285,
                  uiAmountString: "471224821.640285",
                  owner: "FVhQ3QHvXudWSdGix2sdcG47YmrmUxRhf3KCBmiKfekf",
                  insider: false,
                },
                {
                  address: "2ihvNZa8G2fttrnsA6tmtmin8DZVyEd1WmH4RpiGvv7M",
                  amount: 281776485925780,
                  decimals: 6,
                  pct: 4.025829241196646,
                  uiAmount: 281776485.92578,
                  uiAmountString: "281776485.92578",
                  owner: "BmEyv8gu9d4aDm5n96nyC3K328cn5UAR5ddVK1CSF1j2",
                  insider: false,
                },
                {
                  address: "64cmXBSdHeBQ4zK9yVXtVuLMcVUwGg3fvG7fooSqHwmk",
                  amount: 214530048547391,
                  decimals: 6,
                  pct: 3.0650582489871465,
                  uiAmount: 214530048.547391,
                  uiAmountString: "214530048.547391",
                  owner: "Any5gL74oUQy9Psb3goym9STaYMau4CMrTkryS37T7iz",
                  insider: false,
                },
              ],
              freezeAuthority: null,
              mintAuthority: null,
              risks: [
                {
                  name: "Mutable metadata",
                  value: "",
                  description: "Token metadata can be changed by the owner",
                  score: 100,
                  level: "warn",
                },
              ],
              score: 101,
              score_normalised: 7,
              fileMeta: {
                description: "",
                name: "Jupiter",
                symbol: "JUP",
                image: "https://static.jup.ag/jup/icon.png",
              },
              lockerOwners: {},
              lockers: {
                "5Z2YAbbCeagp8kMTAD61fvbT5bcw45Qjubz8t8YobtZR": {
                  programID: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
                  tokenAccount: "11111111111111111111111111111111",
                  owner: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
                  uri: "https://raydium.io/clmm/create-position/?pool_id=5Z2YAbbCeagp8kMTAD61fvbT5bcw45Qjubz8t8YobtZR",
                  unlockDate: 0,
                  usdcLocked: 605.0040784096085,
                  type: "raydium_locker",
                },
                "6tPmZASe4GWd9Rjhg7eB7tLyztv5J9Hgfd4n28ApbA3E": {
                  programID: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
                  tokenAccount: "11111111111111111111111111111111",
                  owner: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
                  uri: "https://raydium.io/liquidity/increase/?mode=add&pool_id=5Qtn7FFKmVH4Brx3V1cR8E4mot2V3eSmvFRBpmKjNy35",
                  unlockDate: 0,
                  usdcLocked: 656.444060908728,
                  type: "raydium_locker",
                },
              },
              markets: [
                {
                  pubkey: "HTrQ634jvG16VQ8uRBD6519WXRrFYi1mzACRqF4KGvkn",
                  marketType: "raydium_clmm",
                  mintA: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
                  mintB: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
                  mintLP: "11111111111111111111111111111111",
                  liquidityA: "69UUnGSgj4c2hgeNjhm28RtZ7HfsvynwGmtcM2NrhYeX",
                  liquidityB: "ZMbwrc9rJfzU4PQCh7QeokyHiY81eM1ayxGEJgJHdSE",
                  mintAAccount: {
                    mintAuthority: null,
                    supply: 6999216038334110,
                    decimals: 6,
                    isInitialized: true,
                    freezeAuthority: null,
                  },
                  mintBAccount: {
                    mintAuthority:
                      "Q6XprfkF8RQQKoQVG33xT88H7wi8Uk1B1CC7YAs69Gi",
                    supply: 2389928539830372,
                    decimals: 6,
                    isInitialized: true,
                    freezeAuthority:
                      "Q6XprfkF8RQQKoQVG33xT88H7wi8Uk1B1CC7YAs69Gi",
                  },
                  mintLPAccount: {
                    mintAuthority: null,
                    supply: 0,
                    decimals: 0,
                    isInitialized: false,
                    freezeAuthority: null,
                  },
                  liquidityAAccount: {
                    mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
                    owner: "HTrQ634jvG16VQ8uRBD6519WXRrFYi1mzACRqF4KGvkn",
                    amount: 1,
                    delegate: null,
                    state: 1,
                    delegatedAmount: 0,
                    closeAuthority: null,
                  },
                  liquidityBAccount: {
                    mint: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
                    owner: "HTrQ634jvG16VQ8uRBD6519WXRrFYi1mzACRqF4KGvkn",
                    amount: 1,
                    delegate: null,
                    state: 1,
                    delegatedAmount: 0,
                    closeAuthority: null,
                  },
                  lp: {
                    baseMint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
                    quoteMint: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
                    lpMint: "11111111111111111111111111111111",
                    quotePrice: 1,
                    basePrice: 0.5098285885931542,
                    base: 0.000001,
                    quote: 0.000001,
                    reserveSupply: 0,
                    currentSupply: 0,
                    quoteUSD: 0.000001,
                    baseUSD: 5.098285885931541e-7,
                    pctReserve: 0,
                    pctSupply: 0,
                    holders: null,
                    totalTokensUnlocked: 0,
                    tokenSupply: 0,
                    lpLocked: 0,
                    lpUnlocked: 0,
                    lpLockedPct: 0,
                    lpLockedUSD: 0,
                    lpMaxSupply: 0,
                    lpCurrentSupply: 0,
                    lpTotalSupply: 0,
                  },
                },
              ],
              totalMarketLiquidity: 9991000.997848028,
              totalLPProviders: 103,
              totalHolders: 846979,
              price: 0.509810146163331,
              rugged: false,
              tokenType: "",
              transferFee: {
                pct: 0,
                maxAmount: 0,
                authority: "11111111111111111111111111111111",
              },
              knownAccounts: {
                "1hs9K8BSC7vNrmaHE1CwAyfdnQ9JdG2APQPQRD21Bpc": {
                  name: "Jupiter Locker",
                  type: "LOCKER",
                },
                GPapprabMX1zcAQTeuDRzrHMyzDN4mzJhDUiLyH2qbN2: {
                  name: "Meteora DLMM Pool",
                  type: "AMM",
                },
                GT5W9SzymWVR6Xk1e9gRpzSryNdn4yxEQYBVTPzSXFe5: {
                  name: "Raydium CLMM Pool",
                  type: "AMM",
                },
              },
              events: [],
              verification: {
                mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
                payer: "",
                name: "Jupiter",
                symbol: "jup",
                description: "",
                jup_verified: true,
                jup_strict: true,
                links: [],
              },
              graphInsidersDetected: 0,
              insiderNetworks: null,
              detectedAt: "2024-05-29T00:40:51.715431226Z",
              creatorTokens: null,
            },
          },
        },
        explanation:
          "Get in depth onchain analysis of JUP to determine if it is a rug pull",
      },
      {
        input: {
          tokenId: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
        },
        output: {
          status: "success",
          message: {
            status: "success",
            response: {
              mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
              tokenProgram: "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
              creator: null,
              creatorBalance: 0,
              token: {
                mintAuthority: null,
                supply: 6999216038334110,
                decimals: 6,
                isInitialized: true,
                freezeAuthority: null,
              },
              token_extensions: null,
              tokenMeta: {
                name: "Jupiter",
                symbol: "JUP",
                uri: "https://static.jup.ag/jup/metadata.json",
                mutable: true,
                updateAuthority: "61aq585V8cR2sZBeawJFt2NPqmN7zDi1sws4KLs5xHXV",
              },
              topHolders: [
                {
                  address: "26ddLrqXDext6caX1gRxARePN4kzajyGiAUz9JmzmTGQ",
                  amount: 2032700001514268,
                  decimals: 6,
                  pct: 29.041823975447294,
                  uiAmount: 2032700001.514268,
                  uiAmountString: "2032700001.514268",
                  owner: "61aq585V8cR2sZBeawJFt2NPqmN7zDi1sws4KLs5xHXV",
                  insider: false,
                },
                {
                  address: "6G4XDSge4txj5tBkA5gZqefXXE3BRxqA37Yb1pmrHv6N",
                  amount: 1700000000001000,
                  decimals: 6,
                  pct: 24.288434457377008,
                  uiAmount: 1700000000.001,
                  uiAmountString: "1700000000.001",
                  owner: "EXJHiMkj6NRFDfhWBMKccHNwdSpCT7tdvQeRf87yHm6T",
                  insider: false,
                },
                {
                  address: "K6U4dQ8jANMEqQQycXYiDcf3172NGefpQBzdDbavQbA",
                  amount: 471224821640285,
                  decimals: 6,
                  pct: 6.732537173583824,
                  uiAmount: 471224821.640285,
                  uiAmountString: "471224821.640285",
                  owner: "FVhQ3QHvXudWSdGix2sdcG47YmrmUxRhf3KCBmiKfekf",
                  insider: false,
                },
                {
                  address: "2ihvNZa8G2fttrnsA6tmtmin8DZVyEd1WmH4RpiGvv7M",
                  amount: 281776485925780,
                  decimals: 6,
                  pct: 4.025829241196646,
                  uiAmount: 281776485.92578,
                  uiAmountString: "281776485.92578",
                  owner: "BmEyv8gu9d4aDm5n96nyC3K328cn5UAR5ddVK1CSF1j2",
                  insider: false,
                },
                {
                  address: "64cmXBSdHeBQ4zK9yVXtVuLMcVUwGg3fvG7fooSqHwmk",
                  amount: 214530048547391,
                  decimals: 6,
                  pct: 3.0650582489871465,
                  uiAmount: 214530048.547391,
                  uiAmountString: "214530048.547391",
                  owner: "Any5gL74oUQy9Psb3goym9STaYMau4CMrTkryS37T7iz",
                  insider: false,
                },
              ],
              freezeAuthority: null,
              mintAuthority: null,
              risks: [
                {
                  name: "Mutable metadata",
                  value: "",
                  description: "Token metadata can be changed by the owner",
                  score: 100,
                  level: "warn",
                },
              ],
              score: 101,
              score_normalised: 7,
              fileMeta: {
                description: "",
                name: "Jupiter",
                symbol: "JUP",
                image: "https://static.jup.ag/jup/icon.png",
              },
              lockerOwners: {},
              lockers: {
                "5Z2YAbbCeagp8kMTAD61fvbT5bcw45Qjubz8t8YobtZR": {
                  programID: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
                  tokenAccount: "11111111111111111111111111111111",
                  owner: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
                  uri: "https://raydium.io/clmm/create-position/?pool_id=5Z2YAbbCeagp8kMTAD61fvbT5bcw45Qjubz8t8YobtZR",
                  unlockDate: 0,
                  usdcLocked: 605.0040784096085,
                  type: "raydium_locker",
                },
                "6tPmZASe4GWd9Rjhg7eB7tLyztv5J9Hgfd4n28ApbA3E": {
                  programID: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
                  tokenAccount: "11111111111111111111111111111111",
                  owner: "675kPX9MHTjS2zt1qfr1NYHuzeLXfQM9H24wFSUt1Mp8",
                  uri: "https://raydium.io/liquidity/increase/?mode=add&pool_id=5Qtn7FFKmVH4Brx3V1cR8E4mot2V3eSmvFRBpmKjNy35",
                  unlockDate: 0,
                  usdcLocked: 656.444060908728,
                  type: "raydium_locker",
                },
              },
              markets: [
                {
                  pubkey: "HTrQ634jvG16VQ8uRBD6519WXRrFYi1mzACRqF4KGvkn",
                  marketType: "raydium_clmm",
                  mintA: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
                  mintB: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
                  mintLP: "11111111111111111111111111111111",
                  liquidityA: "69UUnGSgj4c2hgeNjhm28RtZ7HfsvynwGmtcM2NrhYeX",
                  liquidityB: "ZMbwrc9rJfzU4PQCh7QeokyHiY81eM1ayxGEJgJHdSE",
                  mintAAccount: {
                    mintAuthority: null,
                    supply: 6999216038334110,
                    decimals: 6,
                    isInitialized: true,
                    freezeAuthority: null,
                  },
                  mintBAccount: {
                    mintAuthority:
                      "Q6XprfkF8RQQKoQVG33xT88H7wi8Uk1B1CC7YAs69Gi",
                    supply: 2389928539830372,
                    decimals: 6,
                    isInitialized: true,
                    freezeAuthority:
                      "Q6XprfkF8RQQKoQVG33xT88H7wi8Uk1B1CC7YAs69Gi",
                  },
                  mintLPAccount: {
                    mintAuthority: null,
                    supply: 0,
                    decimals: 0,
                    isInitialized: false,
                    freezeAuthority: null,
                  },
                  liquidityAAccount: {
                    mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
                    owner: "HTrQ634jvG16VQ8uRBD6519WXRrFYi1mzACRqF4KGvkn",
                    amount: 1,
                    delegate: null,
                    state: 1,
                    delegatedAmount: 0,
                    closeAuthority: null,
                  },
                  liquidityBAccount: {
                    mint: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
                    owner: "HTrQ634jvG16VQ8uRBD6519WXRrFYi1mzACRqF4KGvkn",
                    amount: 1,
                    delegate: null,
                    state: 1,
                    delegatedAmount: 0,
                    closeAuthority: null,
                  },
                  lp: {
                    baseMint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
                    quoteMint: "Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB",
                    lpMint: "11111111111111111111111111111111",
                    quotePrice: 1,
                    basePrice: 0.5098285885931542,
                    base: 0.000001,
                    quote: 0.000001,
                    reserveSupply: 0,
                    currentSupply: 0,
                    quoteUSD: 0.000001,
                    baseUSD: 5.098285885931541e-7,
                    pctReserve: 0,
                    pctSupply: 0,
                    holders: null,
                    totalTokensUnlocked: 0,
                    tokenSupply: 0,
                    lpLocked: 0,
                    lpUnlocked: 0,
                    lpLockedPct: 0,
                    lpLockedUSD: 0,
                    lpMaxSupply: 0,
                    lpCurrentSupply: 0,
                    lpTotalSupply: 0,
                  },
                },
              ],
              totalMarketLiquidity: 9991000.997848028,
              totalLPProviders: 103,
              totalHolders: 846979,
              price: 0.509810146163331,
              rugged: false,
              tokenType: "",
              transferFee: {
                pct: 0,
                maxAmount: 0,
                authority: "11111111111111111111111111111111",
              },
              knownAccounts: {
                "1hs9K8BSC7vNrmaHE1CwAyfdnQ9JdG2APQPQRD21Bpc": {
                  name: "Jupiter Locker",
                  type: "LOCKER",
                },
                GPapprabMX1zcAQTeuDRzrHMyzDN4mzJhDUiLyH2qbN2: {
                  name: "Meteora DLMM Pool",
                  type: "AMM",
                },
                GT5W9SzymWVR6Xk1e9gRpzSryNdn4yxEQYBVTPzSXFe5: {
                  name: "Raydium CLMM Pool",
                  type: "AMM",
                },
              },
              events: [],
              verification: {
                mint: "JUPyiwrYJFskUPiHa7hkeR8VUtAeFoSYbKedZNsDvCN",
                payer: "",
                name: "Jupiter",
                symbol: "jup",
                description: "",
                jup_verified: true,
                jup_strict: true,
                links: [],
              },
              graphInsidersDetected: 0,
              insiderNetworks: null,
              detectedAt: "2024-05-29T00:40:51.715431226Z",
              creatorTokens: null,
            },
          },
        },
        explanation:
          "Get in depth onchain analysis of JUP to determine if it is a rug pull",
      },
    ],
  ],
  schema: z.object({
    tokenId: z.string().describe("The token ticker, name or mint address"),
  }),
  handler: async (_agent, input) => {
    try {
      const res = await donutFetchTokenDetailedReport(input.tokenId);
      return {
        status: "success",
        response: res,
      };
    } catch (error: any) {
      return {
        status: "error",
        message: error.message,
      };
    }
  },
};

export { donutRugcheckAction };
